apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.certificate.name }}
spec:
  commonName: {{ .Values.certificate.commonName }}
  dnsNames:
    {{- range .Values.certificate.dnsNames }}
    - {{ . }}
    {{- end }}
  secretName: {{ .Values.certificate.secretName }}
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer