apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "{{ .Values.config.name }}.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "{{ .Values.config.name }}.name" . }}
    helm.sh/chart: {{ include "{{ .Values.config.name }}.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}

data:
  {{- range $key, $value := .Values.environment }}
  {{ $key }}: {{ $value }}
  {{- end }} 