apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "{{ .Values.config.name }}.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "{{ .Values.config.name }}.name" . }}
    helm.sh/chart: {{ include "{{ .Values.config.name }}.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "{{ .Values.config.name }}.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "{{ .Values.config.name }}.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}/app-web:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        envFrom:
        -  configMapRef:
            name: {{ include "{{ .Values.config.name }}.fullname" . }}
