apiVersion: v1
kind: Service
metadata:
  name: {{ include "{{ .Values.config.name }}.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "{{ .Values.config.name }}.name" . }}
    helm.sh/chart: {{ include "{{ .Values.config.name }}.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "{{ .Values.config.name }}.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
